# Generated by Django 4.2.2 on 2023-06-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=150, unique=True)),
                ('year_of_birth', models.IntegerField(blank=True, null=True)),
                ('year_of_death', models.IntegerField(blank=True, null=True)),
                ('number_of_novels', models.IntegerField(blank=True, null=True)),
                ('number_of_novellas', models.IntegerField(blank=True, null=True)),
                ('number_of_volumes_of_poetry', models.IntegerField(blank=True, null=True)),
                ('country_of_origin', models.CharField(choices=[('Unknown', 'Unknown'), ('France', 'France'), ('Poland', 'Poland'), ('Germany', 'Germany'), ('England', 'England'), ('USA', 'Usa')], default='Unknown', max_length=25)),
            ],
        ),
    ]
